version: "3"
services:
  camera-monitor:
    container_name: cogward-camera-monitor-room${ROOM_NUMBER}
    image: 155.230.150.43:5000/camera-monitor:latest
    command: python run.py --room ${ROOM_NUMBER}
    build: .
